# Generated by Django 4.1.7 on 2023-02-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='نام کاربری')),
                ('phone_number', models.IntegerField(default=0, verbose_name='شماره موبایل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('my_ads', models.CharField(max_length=20, verbose_name='آگهی های من')),
                ('my_channel', models.CharField(max_length=20, verbose_name='کانال های من')),
                ('last_seen', models.CharField(max_length=20, verbose_name='آخرین بازدید')),
                ('pay', models.CharField(max_length=20, verbose_name='صورت حساب')),
                ('saved', models.CharField(max_length=20, verbose_name='ذخیره شده ها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
