# Generated by Django 4.1.7 on 2023-02-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('new', models.IntegerField(default=0, verbose_name='قیمت')),
                ('affrodable', models.IntegerField(default=0, verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'قیمت ماشین',
                'verbose_name_plural': 'قیمت ماشین ها',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0, verbose_name='قیمت حال')),
                ('prod', models.IntegerField(default=0, verbose_name='قیمت محصول')),
                ('compare', models.IntegerField(default=0, verbose_name='قیمت مقایسه شده')),
                ('difference', models.IntegerField(default=0, verbose_name='قیمت تفاضل ')),
                ('car', models.IntegerField(default=0, verbose_name='قیمت ماشین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت ها',
            },
        ),
    ]
