# Generated by Django 4.1.7 on 2023-02-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('desc', models.TextField(max_length=1024, verbose_name='توضیحات')),
                ('cover', models.ImageField(upload_to='', verbose_name='عکس اصلی')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس ها')),
                ('year', models.CharField(max_length=20, verbose_name='سال')),
            ],
        ),
        migrations.AddField(
            model_name='ads',
            name='year',
            field=models.CharField(default=None, max_length=20, verbose_name='سال'),
            preserve_default=False,
        ),
    ]
