# Generated by Django 4.1.7 on 2023-02-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_addetail_ads_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addetail',
            options={'verbose_name': 'جزئیات آگهی', 'verbose_name_plural': 'جزئیات '},
        ),
        migrations.AddField(
            model_name='addetail',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='newad',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
