# Generated by Django 4.1.7 on 2023-02-20 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_addetail_options_addetail_price_ads_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.CharField(max_length=200, verbose_name='پایین')),
                ('mid', models.CharField(max_length=200, verbose_name='منصفانه')),
                ('high', models.CharField(max_length=200, verbose_name='بالا')),
                ('function', models.IntegerField(default=0, verbose_name='میزان کارکرد')),
                ('body_status', models.IntegerField(default=0, verbose_name='وضعیت بدنه')),
                ('chassis', models.IntegerField(default=0, verbose_name='وضعیت شاسی ها')),
                ('color', models.CharField(max_length=100, verbose_name='رنگ')),
                ('year', models.IntegerField(default=0, verbose_name='سال تولید')),
            ],
        ),
        migrations.DeleteModel(
            name='AdDetail',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='image_voice',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='video',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='voice',
        ),
        migrations.AddField(
            model_name='priceestimate',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ads'),
        ),
    ]
