# Generated by Django 4.1.7 on 2023-02-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_priceestimate_delete_addetail_remove_ads_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('desc', models.TextField(max_length=1024, verbose_name='توضیحات')),
                ('cover', models.ImageField(upload_to='', verbose_name='عکس اصلی')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس ها')),
                ('year', models.CharField(max_length=20, verbose_name='سال')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'جزئیات آگهی',
                'verbose_name_plural': 'جزئیات ',
            },
        ),
    ]
