# Generated by Django 4.1.7 on 2023-02-20 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_addetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newad',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdDetail', to='ads.ads'),
        ),
    ]
