# Generated by Django 4.1.7 on 2023-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_newad_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('desc', models.TextField(max_length=1024, verbose_name='توضیحات')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('cover', models.ImageField(upload_to='', verbose_name='عکس اصلی')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس ها')),
                ('image_voice', models.ImageField(upload_to='', verbose_name='عکس و صوت')),
                ('video', models.FileField(upload_to='', verbose_name='فیلم')),
                ('voice', models.FileField(upload_to='', verbose_name='صوت')),
                ('state', models.CharField(max_length=20, verbose_name='استان')),
                ('city', models.CharField(max_length=20, verbose_name='شهر')),
                ('sell_type', models.CharField(max_length=20, verbose_name='نوع فروش')),
                ('brand', models.CharField(max_length=20, verbose_name='برند')),
                ('year', models.CharField(max_length=20, verbose_name='سال')),
                ('color', models.CharField(max_length=20, verbose_name='رنگ')),
                ('body', models.CharField(max_length=20, verbose_name='بدنه')),
                ('engine', models.CharField(max_length=20, verbose_name='موتور')),
                ('chassis', models.CharField(max_length=20, verbose_name='شاسی')),
                ('insurance', models.CharField(max_length=20, verbose_name='بیمه')),
                ('is_show', models.BooleanField(default=False, verbose_name='تایید آگهی')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
            ],
        ),
    ]
