# Generated by Django 4.1.7 on 2023-02-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_ad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'آگهی', 'verbose_name_plural': 'آگهی ها '},
        ),
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AlterModelOptions(
            name='priceestimate',
            options={'verbose_name': 'قیمت منصفانه', 'verbose_name_plural': 'نوع قیمت'},
        ),
        migrations.RemoveField(
            model_name='ads',
            name='user',
        ),
        migrations.AlterField(
            model_name='ad',
            name='body',
            field=models.CharField(max_length=20, null=True, verbose_name='بدنه'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='brand',
            field=models.CharField(max_length=20, null=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='chassis',
            field=models.CharField(max_length=20, null=True, verbose_name='شاسی'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.CharField(max_length=20, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='color',
            field=models.CharField(max_length=20, null=True, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='cover',
            field=models.ImageField(null=True, upload_to='', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='engine',
            field=models.CharField(max_length=20, null=True, verbose_name='موتور'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='عکس ها'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_voice',
            field=models.ImageField(null=True, upload_to='', verbose_name='عکس و صوت'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='insurance',
            field=models.CharField(max_length=20, null=True, verbose_name='بیمه'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_show',
            field=models.BooleanField(default=False, null=True, verbose_name='تایید آگهی'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='sell_type',
            field=models.CharField(max_length=20, null=True, verbose_name='نوع فروش'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='state',
            field=models.CharField(max_length=20, null=True, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='video',
            field=models.FileField(null=True, upload_to='', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='voice',
            field=models.FileField(null=True, upload_to='', verbose_name='صوت'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='year',
            field=models.CharField(max_length=20, null=True, verbose_name='سال'),
        ),
    ]
