# Generated by Django 4.1.7 on 2023-02-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_ad_options_alter_ads_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='body',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='بدنه'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='chassis',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شاسی'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='engine',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موتور'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس ها'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_voice',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس و صوت'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='insurance',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='بیمه'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_show',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='تایید آگهی'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='sell_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نوع فروش'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='صوت'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='سال'),
        ),
    ]
