# Generated by Django 4.1.7 on 2023-02-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_ad_body_alter_ad_brand_alter_ad_chassis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس جلد]'),
        ),
    ]
