# Generated by Django 4.1.7 on 2023-03-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_delete_addetail_ad_slug_ad_user_delete_newad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=models.SlugField(verbose_name='آدرس محصول'),
        ),
    ]
