# Generated by Django 4.1.7 on 2023-03-04 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0013_alter_category_slug_alter_product_slug'),
        ('ads', '0013_addetail_remove_ad_slug_remove_ad_user_newad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdDetail',
        ),
        migrations.RemoveField(
            model_name='newad',
            name='ads',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='body',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='chassis',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='color',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='insurance',
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='category.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='آدرس محصول'),
        ),
        migrations.AddField(
            model_name='ad',
            name='type',
            field=models.CharField(default=None, max_length=30, verbose_name='نوع آگهی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='cover',
            field=models.ImageField(default=None, upload_to='image/product/', verbose_name='عکس اصلی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default=None, upload_to='images/product/', verbose_name='عکس ها'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_voice',
            field=models.ImageField(default=None, upload_to='voice-image/product/', verbose_name='عکس صوتی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='video',
            field=models.FileField(default=None, upload_to='video/product/', verbose_name='فیلم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='voice',
            field=models.FileField(default=None, upload_to='voice/product/', verbose_name='صوت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='year',
            field=models.CharField(default=None, max_length=20, verbose_name='سال'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priceestimate',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ad'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('ad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.ad')),
                ('brand', models.CharField(blank=True, max_length=20, verbose_name='برند')),
                ('model', models.CharField(blank=True, max_length=20, verbose_name='مدل')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='رنگ')),
                ('body', models.CharField(blank=True, max_length=20, null=True, verbose_name='بدنه')),
                ('func', models.CharField(blank=True, max_length=20, null=True, verbose_name='کارکرد')),
                ('engine', models.CharField(blank=True, max_length=20, null=True, verbose_name='موتور')),
                ('chassis', models.CharField(blank=True, max_length=20, null=True, verbose_name='شاسی')),
                ('insurance', models.CharField(blank=True, max_length=20, null=True, verbose_name='بیمه')),
            ],
            options={
                'verbose_name': 'آگهی ماشین',
                'verbose_name_plural': 'آگهی های ماشین ',
            },
            bases=('ads.ad',),
        ),
        migrations.DeleteModel(
            name='Ads',
        ),
        migrations.DeleteModel(
            name='NewAd',
        ),
    ]
