# Generated by Django 4.1.7 on 2023-03-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_delete_addetail_remove_newad_ads_remove_ad_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='image/product/', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/', verbose_name='عکس ها'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_voice',
            field=models.ImageField(blank=True, null=True, upload_to='voice-image/product/', verbose_name='عکس صوتی'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/product/', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='voice/product/', verbose_name='صوت'),
        ),
    ]
