# Generated by Django 4.1.7 on 2023-03-04 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_alter_category_options_alter_category_parent_and_more'),
        ('ads', '0015_alter_ad_cover_alter_ad_image_alter_ad_image_voice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='category.category'),
        ),
    ]
