# Generated by Django 4.1.7 on 2023-02-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', 'position'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
