# Generated by Django 4.1.7 on 2023-03-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_category_category_name_product_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.IntegerField(unique=True, verbose_name='شمارش'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی'),
        ),
    ]
