# Generated by Django 4.1.7 on 2023-03-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_alter_category_position_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='آدرس دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='آدرس دسته بندی'),
        ),
    ]
