# Generated by Django 4.1.7 on 2023-03-04 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_subcategory_remove_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='category.category', verbose_name='زیر دسته'),
        ),
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=0, unique=True, verbose_name='شمارش'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان دسته بندی'),
        ),
    ]
