# Generated by Django 4.1.7 on 2023-02-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitro', models.CharField(max_length=20, verbose_name='نیترو')),
                ('zenon', models.CharField(max_length=20, verbose_name='زنون')),
                ('showcase', models.CharField(max_length=20, verbose_name='ویترین')),
                ('upgrade', models.CharField(max_length=20, verbose_name='ارتقا')),
            ],
            options={
                'verbose_name': 'نیترو',
                'verbose_name_plural': 'پلن ها',
            },
        ),
    ]
