# Generated by Django 4.1.7 on 2023-02-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('desc', models.TextField(max_length=1024, verbose_name='توضیحات')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('cover', models.ImageField(upload_to='', verbose_name='عکس اصلی')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس ها')),
                ('image_voice', models.ImageField(upload_to='', verbose_name='عکس صوتی')),
                ('video', models.FileField(upload_to='', verbose_name='فیلم')),
                ('voice', models.FileField(upload_to='', verbose_name='صوت')),
                ('year', models.CharField(max_length=20, verbose_name='سال')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محصولات',
                'verbose_name_plural': 'آگهی ها',
            },
        ),
    ]
