# Generated by Django 4.1.7 on 2023-02-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(upload_to='image/product/', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/product/', verbose_name='عکس ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_voice',
            field=models.ImageField(upload_to='voice-image/product/', verbose_name='عکس صوتی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(upload_to='video/product/', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='voice',
            field=models.FileField(upload_to='voice/product/', verbose_name='صوت'),
        ),
    ]
