# Generated by Django 4.1.7 on 2023-02-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_cover_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='بدنه'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='product',
            name='chassis',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شاسی'),
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موتور'),
        ),
        migrations.AddField(
            model_name='product',
            name='func',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کارکرد'),
        ),
        migrations.AddField(
            model_name='product',
            name='insurance',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='بیمه'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_show',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='تایید آگهی'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='مدل'),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نوع فروش'),
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default=None, max_length=30, verbose_name='نوع آگهی'),
            preserve_default=False,
        ),
    ]
